local args = {
    [1] = {
        ["inputType"] = Enum.UserInputType.MouseButton1,
        ["keyCode"] = Enum.KeyCode.Unknown}}
game:GetService("ReplicatedStorage").Remotes.Input:FireServer(unpack(args))
wait(0,9)
wait(0,9)
wait(0,9)
wait(0,9)
wait(0,9)
wait(0,9)
wait(0,9)
wait(0,9)
wait(0,9)
wait(0,9)
game:GetService("ReplicatedStorage").Remotes.Input:FireServer(unpack(args))
wait(0,9)
wait(0,9)
wait(0,9)
wait(0,9)
wait(0,9)
wait(0,9)
wait(0,9)
wait(0,9)
wait(0,9)
wait(0,9)
game:GetService("ReplicatedStorage").Remotes.Input:FireServer(unpack(args))
wait(0,9)
wait(0,9)
wait(0,9)
wait(0,9)
wait(0,9)
wait(0,9)
wait(0,9)
wait(0,9)
wait(0,9)
wait(0,9)
game:GetService("ReplicatedStorage").Remotes.Input:FireServer(unpack(args))
wait(0,9)
wait(0,9)
wait(0,9)
wait(0,9)
wait(0,9)
wait(0,9)
wait(0,9)
wait(0,9)
wait(0,9)
wait(0,9)
